// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1998
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1998
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1
// License: non-commercial

package alfresco.corba_wrappers.repeatmasker;

//
// IDL:alfresco/corba_wrappers/repeatmasker/RepeatMasker:1.0
//
final public class RepeatMaskerHolder implements org.omg.CORBA.portable.Streamable
{
    public RepeatMasker value;

    public
    RepeatMaskerHolder()
    {
    }

    public
    RepeatMaskerHolder(RepeatMasker initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = RepeatMaskerHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        RepeatMaskerHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return RepeatMaskerHelper.type();
    }
}
