// $Revision: 1.1 $
// $Id: Dba.idl,v 1.1 2003/04/04 11:39:03 niclas Exp $
// IDL for CORBA object for a CpG analysis objects
//
#include "../Server.idl"

module alfresco{
  module corba_wrappers{
    module dba{

      interface Dba : Method {
      };

    };
  };
};
