// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1999
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1999
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1.2
// License: non-commercial

package alfresco.corba_wrappers.dba;

//
// IDL:alfresco/corba_wrappers/dba/Dba:1.0
//
final public class DbaHolder implements org.omg.CORBA.portable.Streamable
{
    public Dba value;

    public
    DbaHolder()
    {
    }

    public
    DbaHolder(Dba initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = DbaHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        DbaHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return DbaHelper.type();
    }
}
