// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1998
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1998
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1
// License: non-commercial

package alfresco.corba_wrappers;

//
// IDL:alfresco/corba_wrappers/GffDataStruct:1.0
//
final public class GffDataStruct
{
    public
    GffDataStruct()
    {
    }

    public
    GffDataStruct(String _ob_a0,
                  String _ob_a1,
                  String[] _ob_a2)
    {
        gff = _ob_a0;
        cgff = _ob_a1;
        suplements = _ob_a2;
    }

    public String gff;
    public String cgff;
    public String[] suplements;
}
