// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1998
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1998
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1
// License: non-commercial

package alfresco.corba_wrappers;

//
// IDL:alfresco/corba_wrappers/InputStruct:1.0
//
final public class InputStruct
{
    public
    InputStruct()
    {
    }

    public
    InputStruct(String[] _ob_a0,
                String[] _ob_a1,
                String[] _ob_a2)
    {
        names = _ob_a0;
        seqs = _ob_a1;
        parameters = _ob_a2;
    }

    public String[] names;
    public String[] seqs;
    public String[] parameters;
}
