// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1998
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1998
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1
// License: non-commercial

package alfresco.corba_wrappers;

//
// IDL:alfresco/corba_wrappers/InputStruct:1.0
//
final public class InputStructHolder implements org.omg.CORBA.portable.Streamable
{
    public InputStruct value;

    public
    InputStructHolder()
    {
    }

    public
    InputStructHolder(InputStruct initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = InputStructHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        InputStructHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return InputStructHelper.type();
    }
}
