// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1998
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1998
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1
// License: non-commercial

package alfresco.corba_wrappers;

//
// IDL:alfresco/corba_wrappers/Method:1.0
//
public interface Method extends org.omg.CORBA.Object
{

    //
    // IDL:alfresco/corba_wrappers/Method/input:1.0
    //
    public void
    input(InputStruct input);

    //
    // IDL:alfresco/corba_wrappers/Method/run:1.0
    //
    public void
    run();

    //
    // IDL:alfresco/corba_wrappers/Method/getGffData:1.0
    //
    public GffDataStruct
    getGffData()
        throws NoOutputException;
}
