// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1998
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1998
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1
// License: non-commercial

package alfresco.corba_wrappers;

//
// IDL:alfresco/corba_wrappers/NoSuchMethodException:1.0
//
final public class NoSuchMethodExceptionHolder implements org.omg.CORBA.portable.Streamable
{
    public NoSuchMethodException value;

    public
    NoSuchMethodExceptionHolder()
    {
    }

    public
    NoSuchMethodExceptionHolder(NoSuchMethodException initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = NoSuchMethodExceptionHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        NoSuchMethodExceptionHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return NoSuchMethodExceptionHelper.type();
    }
}
