// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1998
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1998
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1
// License: non-commercial

package alfresco.corba_wrappers;

//
// IDL:alfresco/corba_wrappers/NoSuchMethodException:1.0
//
final public class NoSuchMethodException extends org.omg.CORBA.UserException
{
    public
    NoSuchMethodException()
    {
    }

    public
    NoSuchMethodException(String _ob_a0)
    {
        reason = _ob_a0;
    }

    public String reason;
}
