// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1998
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1998
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1
// License: non-commercial

package alfresco.corba_wrappers;

//
// IDL:alfresco/corba_wrappers/Server:1.0
//
public interface Server extends org.omg.CORBA.Object
{

    //
    // IDL:alfresco/corba_wrappers/Server/getMethod:1.0
    //
    public Method
    getMethod(String methodName)
        throws NoSuchMethodException;

    //
    // IDL:alfresco/corba_wrappers/Server/getAvailableMethods:1.0
    //
    public String[]
    getAvailableMethods();
}
