// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1998
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1998
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1
// License: non-commercial

package alfresco.corba_wrappers;

//
// IDL:alfresco/corba_wrappers/string_seq:1.0
//
final public class string_seqHolder implements org.omg.CORBA.portable.Streamable
{
    public String[] value;

    public
    string_seqHolder()
    {
    }

    public
    string_seqHolder(String[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = string_seqHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        string_seqHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return string_seqHelper.type();
    }
}
