// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1998
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1998
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1
// License: non-commercial

package alfresco.corba_wrappers;

//
// IDL:alfresco/corba_wrappers/Server:1.0
//
public class StubForServer extends org.omg.CORBA.portable.ObjectImpl
                           implements Server
{
    static final String[] _ob_ids_ =
    {
        "IDL:alfresco/corba_wrappers/Server:1.0",
    };

    public String[]
    _ids()
    {
        return _ob_ids_;
    }

    //
    // IDL:alfresco/corba_wrappers/Server/getMethod:1.0
    //
    public Method
    getMethod(String _ob_a0)
        throws NoSuchMethodException
    {
        org.omg.CORBA.Request _ob_req = _request("getMethod");
        org.omg.CORBA.ORB _ob_orb = _orb();

        _ob_req.exceptions().add(NoSuchMethodExceptionHelper.type());

        org.omg.CORBA.Any _ob_aa0 = _ob_req.add_in_arg();
        _ob_aa0.insert_string(_ob_a0);

        _ob_req.set_return_type(MethodHelper.type());

        _ob_req.invoke();

        java.lang.Exception _ob_ex = _ob_req.env().exception();
        if(_ob_ex != null)
        {
            org.omg.CORBA.UnknownUserException _ob_uex;
            try
            {
                _ob_uex = (org.omg.CORBA.UnknownUserException)_ob_ex;
            }
            catch(ClassCastException _ob_dummy)
            {
                throw (org.omg.CORBA.SystemException)_ob_ex;
            }

            try
            {
                throw NoSuchMethodExceptionHelper.extract(_ob_uex.except);
            }
            catch(org.omg.CORBA.BAD_OPERATION _ob_dummy)
            {
            }

            throw new org.omg.CORBA.UNKNOWN();
        }

        org.omg.CORBA.Any _ob_ra = _ob_req.return_value();
        return MethodHelper.extract(_ob_ra);
    }

    //
    // IDL:alfresco/corba_wrappers/Server/getAvailableMethods:1.0
    //
    public String[]
    getAvailableMethods()
    {
        org.omg.CORBA.Request _ob_req = _request("getAvailableMethods");
        org.omg.CORBA.ORB _ob_orb = _orb();

        _ob_req.set_return_type(string_seqHelper.type());

        _ob_req.invoke();

        java.lang.Exception _ob_ex = _ob_req.env().exception();
        if(_ob_ex != null)
            throw (org.omg.CORBA.SystemException)_ob_ex;

        org.omg.CORBA.Any _ob_ra = _ob_req.return_value();
        return string_seqHelper.extract(_ob_ra);
    }
}
