// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1998
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1998
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1
// License: non-commercial

package alfresco.corba_wrappers.est_genome;

//
// IDL:alfresco/corba_wrappers/est_genome/Est_Genome:1.0
//
final public class Est_GenomeHolder implements org.omg.CORBA.portable.Streamable
{
    public Est_Genome value;

    public
    Est_GenomeHolder()
    {
    }

    public
    Est_GenomeHolder(Est_Genome initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = Est_GenomeHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        Est_GenomeHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return Est_GenomeHelper.type();
    }
}
