// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1998
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1998
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1
// License: non-commercial

package alfresco.corba_wrappers.blastwise;

//
// IDL:alfresco/corba_wrappers/blastwise/BlastWise:1.0
//
final public class BlastWiseHolder implements org.omg.CORBA.portable.Streamable
{
    public BlastWise value;

    public
    BlastWiseHolder()
    {
    }

    public
    BlastWiseHolder(BlastWise initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = BlastWiseHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        BlastWiseHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return BlastWiseHelper.type();
    }
}
