// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1998
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1998
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1.1
// License: non-commercial

package alfresco.corba_wrappers.genewise;

//
// IDL:alfresco/corba_wrappers/genewise/Genewise:1.0
//
public interface Genewise extends alfresco.corba_wrappers.Method
{
}
