// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1998
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1998
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1.1
// License: non-commercial

package alfresco.corba_wrappers.genewise;

//
// IDL:alfresco/corba_wrappers/genewise/Genewise:1.0
//
final public class GenewiseHolder implements org.omg.CORBA.portable.Streamable
{
    public Genewise value;

    public
    GenewiseHolder()
    {
    }

    public
    GenewiseHolder(Genewise initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = GenewiseHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        GenewiseHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return GenewiseHelper.type();
    }
}
