// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1999
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1999
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1.2
// License: non-commercial

package alfresco.corba_wrappers.spidey;

//
// IDL:alfresco/corba_wrappers/spidey/Spidey:1.0
//
public interface Spidey extends alfresco.corba_wrappers.Method
{
}
