// $Revision: 1.1 $
// $Id: BlGenewise.idl,v 1.1 2003/04/04 11:38:48 niclas Exp $
// IDL for CORBA object for a BlGenewise analysis objects
//
#include "../Server.idl"

module alfresco{
  module corba_wrappers{
    module blgenewise{

      interface BlGenewise : Method {
      };

    };
  };
};
