// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1998
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1998
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1
// License: non-commercial

package alfresco.corba_wrappers.blgenewise;

//
// IDL:alfresco/corba_wrappers/blgenewise/BlGenewise:1.0
//
final public class BlGenewiseHolder implements org.omg.CORBA.portable.Streamable
{
    public BlGenewise value;

    public
    BlGenewiseHolder()
    {
    }

    public
    BlGenewiseHolder(BlGenewise initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = BlGenewiseHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        BlGenewiseHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return BlGenewiseHelper.type();
    }
}
