// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1998
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1998
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1
// License: non-commercial

package alfresco.corba_wrappers.blastalign;

//
// IDL:alfresco/corba_wrappers/blastalign/BlastAlign:1.0
//
public interface BlastAlign extends alfresco.corba_wrappers.Method
{
}
