// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1998
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1998
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1
// License: non-commercial

package alfresco.server;

//
// IDL:alfresco/server/AlfrescoServer:1.0
//
final public class AlfrescoServerHolder implements org.omg.CORBA.portable.Streamable
{
    public AlfrescoServer value;

    public
    AlfrescoServerHolder()
    {
    }

    public
    AlfrescoServerHolder(AlfrescoServer initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = AlfrescoServerHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        AlfrescoServerHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return AlfrescoServerHelper.type();
    }
}
