// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1998
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1998
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1
// License: non-commercial

package alfresco.server;

//
// IDL:alfresco/server/AlfrescoServer:1.0
//
public interface AlfrescoServer extends org.omg.CORBA.Object
{

    //
    // IDL:alfresco/server/AlfrescoServer/getNames:1.0
    //
    public String[]
    getNames();

    //
    // IDL:alfresco/server/AlfrescoServer/getPair:1.0
    //
    public PairStruct
    getPair(String name);
}
