// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1998
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1998
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1
// License: non-commercial

package alfresco.server;

//
// IDL:alfresco/server/PairStruct:1.0
//
final public class PairStructHelper
{
    public static void
    insert(org.omg.CORBA.Any any, PairStruct val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static PairStruct
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equal(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[4];

            members[0] = new org.omg.CORBA.StructMember();
            members[0].name = "fasta1";
            members[0].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_string);

            members[1] = new org.omg.CORBA.StructMember();
            members[1].name = "fasta2";
            members[1].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_string);

            members[2] = new org.omg.CORBA.StructMember();
            members[2].name = "gff";
            members[2].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_string);

            members[3] = new org.omg.CORBA.StructMember();
            members[3].name = "cgff";
            members[3].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_string);

            typeCode_ = orb.create_struct_tc(id(), "PairStruct", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:alfresco/server/PairStruct:1.0";
    }

    public static PairStruct
    read(org.omg.CORBA.portable.InputStream in)
    {
        PairStruct val = new PairStruct();
        val.fasta1 = in.read_string();
        val.fasta2 = in.read_string();
        val.gff = in.read_string();
        val.cgff = in.read_string();
        return val;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, PairStruct val)
    {
        out.write_string(val.fasta1);
        out.write_string(val.fasta2);
        out.write_string(val.gff);
        out.write_string(val.cgff);
    }
}
