// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1998
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1998
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1
// License: non-commercial

package alfresco.server;

//
// IDL:alfresco/server/PairStruct:1.0
//
final public class PairStructHolder implements org.omg.CORBA.portable.Streamable
{
    public PairStruct value;

    public
    PairStructHolder()
    {
    }

    public
    PairStructHolder(PairStruct initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = PairStructHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        PairStructHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return PairStructHelper.type();
    }
}
