// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1998
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1998
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1
// License: non-commercial

package alfresco.server;

//
// IDL:alfresco/server/PairStruct:1.0
//
final public class PairStruct
{
    public
    PairStruct()
    {
    }

    public
    PairStruct(String _ob_a0,
               String _ob_a1,
               String _ob_a2,
               String _ob_a3)
    {
        fasta1 = _ob_a0;
        fasta2 = _ob_a1;
        gff = _ob_a2;
        cgff = _ob_a3;
    }

    public String fasta1;
    public String fasta2;
    public String gff;
    public String cgff;
}
