// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1998
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1998
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1
// License: non-commercial

package alfresco.corba_wrappers.blest_genome;

//
// IDL:alfresco/corba_wrappers/blest_genome/BlEst_Genome:1.0
//
final public class BlEst_GenomeHolder implements org.omg.CORBA.portable.Streamable
{
    public BlEst_Genome value;

    public
    BlEst_GenomeHolder()
    {
    }

    public
    BlEst_GenomeHolder(BlEst_Genome initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = BlEst_GenomeHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        BlEst_GenomeHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return BlEst_GenomeHelper.type();
    }
}
